---
- name: Download & install clients
  ansible.builtin.include_tasks: install-client.yml
  vars:
    url: "{{ download_urls[client_name] }}"
    filename: "{{ (openshift_clients_install_dir, client_name) | path_join }}"
  loop: "{{ openshift_clients }}"
  loop_control:
    loop_var: client_name
